.nh
.TH "FGT" "1" "Sep 2026" "fgt" "fgt Manual"

.SH NAME
fgt-system-snmp-user-set - Update fields on a user object


.SH SYNOPSIS
\fBfgt system snmp user set  [flags]\fP


.SH DESCRIPTION
Update fields on a user object


.SH OPTIONS
\fB--auth-proto\fP=""
	md5|sha|sha224|sha256|sha384|sha512

.PP
\fB--auth-pwd\fP=""
	auth password

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--notify-hosts\fP=""
	trap destination IP(s)

.PP
\fB--priv-proto\fP=""
	aes|des|aes256|aes256cisco

.PP
\fB--priv-pwd\fP=""
	privacy password

.PP
\fB--queries\fP=""
	enable|disable

.PP
\fB--security-level\fP=""
	no-auth-no-priv|auth-no-priv|auth-priv

.PP
\fB--set\fP=[]
	set an arbitrary field: --set key=value (repeatable; value may be a,b for ref lists)

.PP
\fB--status\fP=""
	enable|disable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--column\fP=[]
	select/order output columns (repeatable)

.PP
\fB--context\fP=""
	config context to use

.PP
\fB--debug\fP[=false]
	log request/response metadata to stderr

.PP
\fB-o\fP, \fB--format\fP=""
	output format: table|json|yaml|csv|value

.PP
\fB--insecure\fP[=false]
	skip TLS verification (footgun)

.PP
\fB--no-headers\fP[=false]
	omit table/csv headers

.PP
\fB--password\fP=""
	admin password for session auth (prefer a secret_ref or FGT_CLI_PASSWORD)

.PP
\fB--profile\fP=""
	config profile to use

.PP
\fB--server\fP=""
	FortiGate API base URL (e.g. https://fw.example.com)

.PP
\fB--sort\fP=""
	sort by column (NAME[:asc|desc])

.PP
\fB--tls-fingerprint\fP=""
	pin the server cert SHA-256 fingerprint

.PP
\fB--token\fP=""
	REST API token (prefer a config secret_ref or FGT_CLI_TOKEN)

.PP
\fB--user\fP=""
	admin username for session auth (or FGT_CLI_USER)

.PP
\fB--vdom\fP=""
	target VDOM (default: device global/root)

.PP
\fB--wide\fP[=false]
	do not truncate wide table columns

.PP
\fB-y\fP, \fB--yes\fP[=false]
	assume yes for destructive confirmations


.SH SEE ALSO
\fBfgt-system-snmp-user(1)\fP
