.nh
.TH "FGT" "1" "Sep 2026" "fgt" "fgt Manual"

.SH NAME
fgt-user-radius-set - Update fields on a radius object


.SH SYNOPSIS
\fBfgt user radius set  [flags]\fP


.SH DESCRIPTION
Update fields on a radius object


.SH OPTIONS
\fB--auth-type\fP=""
	auto|ms_chap_v2|ms_chap|chap|pap

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--nas-ip\fP=""
	NAS IP / called-station-id

.PP
\fB--secondary-server\fP=""
	failover RADIUS server

.PP
\fB--secret\fP=""
	shared secret

.PP
\fB--server\fP=""
	primary RADIUS server

.PP
\fB--set\fP=[]
	set an arbitrary field: --set key=value (repeatable; value may be a,b for ref lists)

.PP
\fB--timeout\fP=""
	seconds


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--column\fP=[]
	select/order output columns (repeatable)

.PP
\fB--context\fP=""
	config context to use

.PP
\fB--debug\fP[=false]
	log request/response metadata to stderr

.PP
\fB-o\fP, \fB--format\fP=""
	output format: table|json|yaml|csv|value

.PP
\fB--insecure\fP[=false]
	skip TLS verification (footgun)

.PP
\fB--no-headers\fP[=false]
	omit table/csv headers

.PP
\fB--password\fP=""
	admin password for session auth (prefer a secret_ref or FGT_CLI_PASSWORD)

.PP
\fB--profile\fP=""
	config profile to use

.PP
\fB--sort\fP=""
	sort by column (NAME[:asc|desc])

.PP
\fB--tls-fingerprint\fP=""
	pin the server cert SHA-256 fingerprint

.PP
\fB--token\fP=""
	REST API token (prefer a config secret_ref or FGT_CLI_TOKEN)

.PP
\fB--user\fP=""
	admin username for session auth (or FGT_CLI_USER)

.PP
\fB--vdom\fP=""
	target VDOM (default: device global/root)

.PP
\fB--wide\fP[=false]
	do not truncate wide table columns

.PP
\fB-y\fP, \fB--yes\fP[=false]
	assume yes for destructive confirmations


.SH SEE ALSO
\fBfgt-user-radius(1)\fP
