.nh
.TH "FGT" "1" "Sep 2026" "fgt" "fgt Manual"

.SH NAME
fgt-router-bgp-set - Update fields on a bgp object


.SH SYNOPSIS
\fBfgt router bgp set [flags]\fP


.SH DESCRIPTION
Update fields on a bgp object


.SH OPTIONS
\fB--as\fP=""
	local AS number (supports asdot)

.PP
\fB--ebgp-multipath\fP=""
	enable|disable

.PP
\fB--graceful-restart\fP=""
	enable|disable

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--holdtime-timer\fP=""
	holdtime timer in seconds

.PP
\fB--ibgp-multipath\fP=""
	enable|disable

.PP
\fB--keepalive-timer\fP=""
	keepalive timer in seconds

.PP
\fB--router-id\fP=""
	BGP router-id (IPv4)

.PP
\fB--set\fP=[]
	set an arbitrary field: --set key=value (repeatable; value may be a,b for ref lists)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--column\fP=[]
	select/order output columns (repeatable)

.PP
\fB--context\fP=""
	config context to use

.PP
\fB--debug\fP[=false]
	log request/response metadata to stderr

.PP
\fB-o\fP, \fB--format\fP=""
	output format: table|json|yaml|csv|value

.PP
\fB--insecure\fP[=false]
	skip TLS verification (footgun)

.PP
\fB--no-headers\fP[=false]
	omit table/csv headers

.PP
\fB--password\fP=""
	admin password for session auth (prefer a secret_ref or FGT_CLI_PASSWORD)

.PP
\fB--profile\fP=""
	config profile to use

.PP
\fB--server\fP=""
	FortiGate API base URL (e.g. https://fw.example.com)

.PP
\fB--sort\fP=""
	sort by column (NAME[:asc|desc])

.PP
\fB--tls-fingerprint\fP=""
	pin the server cert SHA-256 fingerprint

.PP
\fB--token\fP=""
	REST API token (prefer a config secret_ref or FGT_CLI_TOKEN)

.PP
\fB--user\fP=""
	admin username for session auth (or FGT_CLI_USER)

.PP
\fB--vdom\fP=""
	target VDOM (default: device global/root)

.PP
\fB--wide\fP[=false]
	do not truncate wide table columns

.PP
\fB-y\fP, \fB--yes\fP[=false]
	assume yes for destructive confirmations


.SH SEE ALSO
\fBfgt-router-bgp(1)\fP
